<div class="va-catalog-page">
    <div class="va-catalog-heading"><div><span class="va-eyebrow">V Auto Spare</span><h1>Browse Cars</h1></div><nav aria-label="breadcrumb"><ol class="breadcrumb mb-0"><li class="breadcrumb-item"><a href="<?= base_url() ?>">Home</a></li><li class="breadcrumb-item active">Cars</li></ol></nav></div>
    <div class="va-catalog-layout">
        <aside class="va-filter-panel"><form method="get" action="<?= base_url('cars') ?>" id="filterForm">
            <section class="va-filter-section"><h2>Car Brand <i class="bi bi-dash"></i></h2><select name="brand" class="form-select form-select-sm" id="filterBrand"><option value="">All brands</option><?php foreach ($brands as $brand): ?><option value="<?= $brand->id ?>" <?= ($filters['brand_id'] ?? '') == $brand->id ? 'selected' : '' ?>><?= html_escape($brand->name) ?></option><?php endforeach; ?></select></section>
            <section class="va-filter-section"><h2>Model <i class="bi bi-dash"></i></h2><select name="model" class="form-select form-select-sm" id="filterModel"><option value="">All models</option><?php foreach ($models as $model): ?><option value="<?= $model->id ?>" <?= ($filters['model_id'] ?? '') == $model->id ? 'selected' : '' ?>><?= html_escape($model->name) ?></option><?php endforeach; ?></select></section>
            <section class="va-filter-section"><h2>Fuel Type <i class="bi bi-dash"></i></h2><div class="va-filter-options"><?php foreach ($fuel_types as $fuel): ?><label><input type="radio" name="fuel" value="<?= $fuel->id ?>" <?= ($filters['fuel_type_id'] ?? '') == $fuel->id ? 'checked' : '' ?>> <span><?= html_escape($fuel->name) ?></span></label><?php endforeach; ?></div></section>
            <section class="va-filter-section"><h2>Price Filter <i class="bi bi-dash"></i></h2><div class="row g-2"><div class="col-6"><input type="number" name="min_price" class="form-control form-control-sm" placeholder="Min" value="<?= html_escape($filters['min_price'] ?? '') ?>"></div><div class="col-6"><input type="number" name="max_price" class="form-control form-control-sm" placeholder="Max" value="<?= html_escape($filters['max_price'] ?? '') ?>"></div></div></section>
            <section class="va-filter-section"><h2>Search <i class="bi bi-dash"></i></h2><input type="search" name="keyword" class="form-control form-control-sm" placeholder="Search cars" value="<?= html_escape($filters['keyword'] ?? '') ?>"></section><button class="btn va-filter-submit w-100">Apply Filters</button><a href="<?= base_url('cars') ?>" class="va-filter-reset">Reset all filters</a>
        </form></aside>
        <section class="va-catalog-results"><div class="va-catalog-toolbar"><span>Showing <?= $total ? (($page - 1) * 12 + 1) : 0 ?>–<?= min($page * 12, $total) ?> of <?= $total ?> cars</span><select class="form-select form-select-sm" onchange="window.location.href=this.value"><?php $query = array_merge($_GET, ['sort' => 'newest']); ?><option value="<?= base_url('cars').'?'.http_build_query($query) ?>">Newest first</option><?php $query['sort'] = 'price_low'; ?><option value="<?= base_url('cars').'?'.http_build_query($query) ?>">Price: low to high</option><?php $query['sort'] = 'price_high'; ?><option value="<?= base_url('cars').'?'.http_build_query($query) ?>">Price: high to low</option></select></div>
        <?php if (empty($cars)): ?><div class="va-empty-catalog"><i class="bi bi-search"></i><h2>No cars found</h2><p>Try changing your filters or search term.</p></div><?php else: ?><div class="va-catalog-grid va-car-catalog-grid"><?php foreach ($cars as $car): $url = base_url('car/'.$car->id.'/'.url_title($car->brand_name.'-'.$car->model_name, '-', TRUE)); ?><article class="va-catalog-card"><a href="<?= $url ?>" class="va-catalog-image"><?php if ($car->primary_image): ?><img src="<?= $car->primary_image ?>" alt="<?= html_escape($car->brand_name.' '.$car->model_name) ?>"><?php else: ?><i class="bi bi-car-front"></i><?php endif; ?></a><div class="va-catalog-card-body"><h2><a href="<?= $url ?>"><?= html_escape($car->brand_name.' '.$car->model_name) ?></a></h2><p class="va-car-meta"><?= $car->year ?> · <?= html_escape($car->fuel_type) ?> · <?= html_escape($car->transmission) ?></p><strong>&#8377; <?= number_format($car->price / 100000, 1) ?> Lakh</strong><a href="<?= $url ?>" class="btn va-card-button">View Details</a></div></article><?php endforeach; ?></div><?php endif; ?></section>
    </div>
</div>
<script>$('#filterBrand').change(function(){var id=$(this).val(); if(!id){$('#filterModel').html('<option value="">All models</option>');return;} $.get('<?= base_url('cars/models_by_brand') ?>?brand_id='+id,function(data){var options='<option value="">All models</option>'; $.each(data,function(_,model){options+='<option value="'+model.id+'">'+model.name+'</option>';});$('#filterModel').html(options);});});</script>
